CREATE TABLE IF NOT EXISTS default.reservations_transformed (
    id               Int32,
    csv_upload_id    Int32,
    reservation_id   Nullable(Int32),
    guest_id         Nullable(String),
    guest_name       Nullable(String),
    room_number      String,
    room_type        Nullable(String),
    arrangement      Nullable(String),
    in_house_date    Nullable(String),
    arrival_date     DateTime64(3),
    depart_date      DateTime64(3),
    created_date     Nullable(String),
    birth_date       Nullable(String),
    check_in_time    Nullable(String),
    check_out_time   Nullable(String),
    age              Nullable(Int32),
    member_no        Nullable(String),
    member_type      Nullable(String),
    email            Nullable(String),
    mobile_phone     Nullable(String),
    vip_status       Nullable(String),
    room_rate        Nullable(Decimal(18,2)),
    lodging          Nullable(Decimal(18,2)),
    breakfast        Nullable(Decimal(18,2)),
    lunch            Nullable(Decimal(18,2)),
    dinner           Nullable(Decimal(18,2)),
    other_charges    Nullable(Decimal(18,2)),
    bill_number      Nullable(String),
    pay_article      Nullable(String),
    rate_code        Nullable(String),
    adult_count      Nullable(Int32),
    child_count      Nullable(Int32),
    compliment       Nullable(String),
    nationality      Nullable(String),
    local_region     Nullable(String),
    company_ta       Nullable(String),
    sob              Nullable(String),
    nights           Nullable(Int32),
    segment          Nullable(String),
    created_by       Nullable(String),
    k_card           Nullable(String),
    remarks          Nullable(String),
    created_at       Nullable(DateTime64(3)),
    deleted_at       Nullable(DateTime64(3)),
    ingested_at      DateTime DEFAULT toTimeZone(now(), 'Asia/Jakarta'),
    version          UInt32   DEFAULT toUInt32(toUnixTimestamp(now()))
)
ENGINE = ReplacingMergeTree(version)
PRIMARY KEY id
ORDER BY id
SETTINGS index_granularity = 8192;
